context:
  name: display3d
  version: "0.2.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/renpenguin/display3d/archive/v${{ version }}.tar.gz
  sha256: 1dd0cb10b75b125453d55f1385d0245d9ec14969eb29da74fa68de58772bd8fa

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - display3d --version

about:
  homepage: https://github.com/renpenguin/display3d
  summary: A command line interface for rendering and animating 3D objects
  description: display3d is a command line interface for rendering and animating 3D objects using ANSI escape codes, written using gemini-engine in the Rust programming language.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/renpenguin/display3d

extra:
  recipe-maintainers:
    - pavelzw
