context:
  name: display3d
  version: '0.2.1'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/renpenguin/display3d/archive/v${{ version }}.tar.gz
  sha256: 9eb86c960cffaf1a49c727bf18969624d29e2b84b6fccf60d97bff5dc1282429

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - display3d --version

about:
  homepage: https://github.com/renpenguin/display3d
  summary: A command line interface for rendering and animating 3D objects
  description: display3d is a command line interface for rendering and animating 3D objects using ANSI escape codes, written using gemini-engine in the Rust programming language.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/renpenguin/display3d

extra:
  recipe-maintainers:
    - pavelzw
